### ISSUE TITLE
chore: to-do refactor

### ISSUE THREAD

**Issue by vmarchaud** [keymetrics/pm2-io-apm#212]
- [x] deepmetrics -> dropped
- [ ] v8 space memory metrics
- [x] configuration -> giving up
- [x] metric implementation
- [x] error middlewares
- [x] https://github.com/keymetrics/pm2-io-agent-node/releases/tag/v1.0.11
- [x] coverage
